[build]
  command = "npm install && npm run build && npm run build:ssr"
  publish = "dist/fish-market/browser"
  functions = "dist/fish-market/server"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@angular/platform-server"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
